version: "3"

services:
    alfresco:
        image: alfresco/alfresco-governance-repository-community:latest
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dalfresco.host=localhost
                -Dalfresco.port.ssl=80
                -Dalfresco.protocol=http
                -Dalfresco.port=8080
                -Dshare.host=localhost
                -Dshare.port=8181
                "
        ports:
            - 8080:8080
    share:
        image: alfresco/alfresco-governance-share-community:latest
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
        ports:
            - 8181:8080

    postgres:
        image: library/postgres:${POSTGRES_TAG}
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:${SOLR6_TAG}
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        ports:
            - 8083:8983 #Browser port
