version: "2"

services:
    alfresco:
        build:
            context: jrebel-repo
        environment:
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.restApi.basicAuthScheme=true
                -Dimap.server.enabled=true
                -Dftp.enabled=true
                -Dftp.dataPortFrom=30000
                -Dftp.dataPortTo=30099
                -Dshare.host=localhost
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(tcp://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -agentpath:/usr/local/tomcat/jrebel/lib/libjrebel64.so
                -Drebel.remoting_plugin=true
                -Drebel.log.file=/jrebel.log
                -Drebel.remoting_port=12345
                "
        ports:
            - 8080:8080
            - 12345:12345 #jRebel port
